### ISSUE TITLE
Can't run mxpp

### ISSUE THREAD

**Issue by tfreedman** [anewusername/mxpp#1]
~/mxpp$ python3 -m mxpp.main
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/lib/python3.4/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/tyler/mxpp/mxpp/main.py", line 53
    self.xmpp = ClientXMPP(**self.xmpp_login, **self.xmpp_roster_options)
                                            ^
SyntaxError: invalid syntax

**Comment by anewusername** [comment]
Looks like a python 3.4 vs 3.5 issue -- I've pushed a fix to a new branch (py3.4), but I haven't tested on python 3.4 much and I'll likely continue to focus on >=3.5 in the future.

**Comment by tfreedman** [comment]
The new branch fixes the last error, but now it just hits a different error

```~/mxpp$ python3 -m mxpp.main
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tyler/mxpp/mxpp/main.py", line 2, in <module>
    from typing import Dict, Tuple, List
ImportError: No module named 'typing'```

If you have no intention of supporting Python 3.4 (and I can't blame you), just change the project's documentation to say that it requires >= 3.5. I set up Python 3.5 and it works.

**Comment by anewusername** [comment]
Oops, forgot to include typing in ```requirements.txt```. I've fixed that and updated the docs, thanks!
