### ISSUE TITLE
Python 3.7 Support ?

### ISSUE THREAD

**Issue by DoM1niC** [anewusername/mxpp#13]
I got this Error
```
python@webapps:~/matrix-appservice-xmpp$ python3 -m mxpp.main
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/projects/python/matrix-appservice-xmpp/mxpp/main.py", line 484
    if from_jid not in self.xmpp.jid_nick_map.keys():
     ^
IndentationError: expected an indented block
```
I don't whats wrong the other Python based bridges works well & pip3 installed als dependencies...

**Comment by anewusername** [comment]
Should be fixed now, thanks for the report.
