### ISSUE TITLE
[Error] kind of SSL/TLS error?

### ISSUE THREAD

**Issue by DoM1niC** [anewusername/mxpp#14]
Hey folks,
I use a Prosody Server with XMPP in combine with Letsencrypt Certs, behind an NGINX Stream Proxy, all Clients & external Web Clients works well with my Setup but this Bridge report following error.

**Error from Bridge**
```
ERROR    Connection error.
ERROR    <TagSet object at 0x7f354c251ed0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f354c251950 tagSet <TagSet object at 0x7f354d082f50 tags 0:0:4> encoding iso-8859-1>
Traceback (most recent call last):
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1492, in _process
    if not self.__read_xml():
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1564, in __read_xml
    self.__spawn_event(xml)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1632, in __spawn_event
    handler.prerun(stanza_copy)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_starttls_proceed
    if self.xmpp.start_tls():
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 889, in start_tls
    cert.verify(self._expected_server_name, self._der_cert)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/cert.py", line 134, in verify
    cert_names = extract_names(raw_cert)
  File "/home/projects/python/.local/lib/python3.7/site-packages/sleekxmpp/xmlstream/cert.py", line 73, in extract_names
    asn1Spec=OctetString())[0]
  File "/usr/lib/python3/dist-packages/pyasn1/codec/ber/decoder.py", line 1318, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: <TagSet object at 0x7f354c251ed0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f354c251950 tagSet <TagSet object at 0x7f354d082f50 tags 0:0:4> encoding iso-8859-1>
INFO     XMPP Disconnected!
```

**Prosody Vhost**

```
VirtualHost "3dns.eu"
      authentication = 'ldap2'
        storage = {
        roster = "internal";
        vcard = "ldap";
}

 ssl = { 
            key = "/etc/letsencrypt/live/3dns.eu/privkey.pem";
            certificate = "/etc/letsencrypt/live/3dns.eu/fullchain.pem";
		}
	enabled = true 
```

**NGINX Stream Conf**

```
    server {
        listen 5222 reuseport so_keepalive=on;
        proxy_pass 10.10.0.3:5222;
	    ssl_preread on;
    }
    server {
        listen 5269 reuseport so_keepalive=on;
        proxy_pass 10.10.0.3:5269;
    }
    server {
        listen 5280 reuseport so_keepalive=on;
        proxy_pass 10.10.0.3:5280;
    }
    server {
        listen 5281 reuseport so_keepalive=on;
        proxy_pass 10.10.0.3:5280;
	    ssl_preread on;
    }
```

**Comment by anewusername** [comment]
May be a pyasn1 issue: https://github.com/etingof/pyasn1/issues/112
Can you check your pyasn1 version with `import pyasn1; print(pyasn1.__version__)` ?

**Comment by DoM1niC** [comment]
```
>>> import pyasn1; print(pyasn1.__version__)
0.2.1

```

**Comment by anewusername** [comment]
That's actually quite old (early 2017)  -- I vaguely recall having similar issues back then, which got resolved with pyasn1 or sleekXMPP updates pretty soon afterwards. Are you able to upgrade to a more recent version?

I'm currently running with the following versions:
```
>>> import pyasn1; print(pyasn1.__version__)
0.4.2

>>> import sleekxmpp; print(sleekxmpp.__version__)
1.3.3
```

**Comment by DoM1niC** [comment]
```

Python 3.7.5 (default, Oct 27 2019, 15:43:29)
[GCC 9.2.1 20191022] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyasn1; print(pyasn1.__version__)
0.4.7
>>> import sleekxmpp; print(sleekxmpp.__version__)
1.3.3
>>>
```
But isn't change the Issue :(

**Comment by DoM1niC** [comment]
I fixed my Problem now :) 
```
git clone https://github.com/anewusername/mxpp.git
cd mxpp
virtualenv -p python3.8 ./
source ./bin/activate
pip3.8 install -r requirements.txt
python -m mxpp.main
```
All working now without any crashes.... 

THX anyway :+1:
