### ISSUE TITLE
After leaving the MUC and send purge I got this

### ISSUE THREAD

**Issue by szimszon** [anewusername/mxpp#4]
Hi,

Really nice bot. Thank you.

The traceback:

 INFO     Leaving room !ZOXXXXXXXXXYvjWp:XXXXXXXXXXXXXXXXX (None) [<groupchat-i>XXXXXXXXXXX@conference.XXXXXXXXXXXXXXXXXXXXXX]
 ERROR    Exception thrown during sync
 Traceback (most recent call last):
   File "/opt/mxpp/src/matrix-client/matrix_client/client.py", line 338, in listen_forever
     self._sync(timeout_ms)
   File "/opt/mxpp/src/matrix-client/matrix_client/client.py", line 462, in _sync
     room._put_event(event)
   File "/opt/mxpp/src/matrix-client/matrix_client/room.py", line 267, in _put_event
     listener['callback'](self, event)
   File "/opt/mxpp/mxpp/main.py", line 265, in matrix_control_message
     self.xmpp.plugin['xep_0045'].leaveMUC(room_jid)
 TypeError: leaveMUC() missing 1 required positional argument: 'nick'

**Comment by anewusername** [comment]
Should be fixed now, thanks!

**Comment by szimszon** [comment]
Confirmed. It works. Thank you. I also switched to Ubuntu 17.04 as docker base and python3.5.
