### ISSUE TITLE
After leavemuc command I tried to rejoin with joinmuc but I got this

### ISSUE THREAD

**Issue by szimszon** [anewusername/mxpp#5]
Hi,

Traceback:
 DEBUG    matrix_control_message: !qGcXXXXXXXXXXXXXIKMgN:XXXXXXXXXXXXXXX  {'type': 'm.room.message', 'unsigned': {'age': 65}, 'origin_server_ts': 1495643369572, 'sender': '@XXXXXXXXXXXXX:XXXXXXXXXXXXX', 'room_id': '!qGcXXXXXXXXXXXIKMgN:XXXXXXXXXXXXXXXX', 'content': {'msgtype': 'm.text', 'body': 'joinmuc XXXXXXXXXX@conference.XXXXXXXXXXXXXXXXXXXXXXXXXXX'}, 'event_id': '$1495643XXXXXXXXXXXXwoBE:XXXXXXXXXXXXXXXXXXXX'}
 INFO     Matrix received control message: joinmuc XXXXXXXXXXXXXX@conference.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 INFO     XMPP MUC join: XXXXXXXXX@conference.XXXXXXXXXXXXXXXX
 ERROR    Exception thrown during sync
 Traceback (most recent call last):
   File "/opt/mxpp/src/matrix-client/matrix_client/client.py", line 338, in listen_forever
     self._sync(timeout_ms)
   File "/opt/mxpp/src/matrix-client/matrix_client/client.py", line 462, in _sync
     room._put_event(event)
   File "/opt/mxpp/src/matrix-client/matrix_client/room.py", line 267, in _put_event
     listener['callback'](self, event)
   File "/opt/mxpp/mxpp/main.py", line 271, in matrix_control_message
     self.create_groupchat_room(room_jid)
   File "/opt/mxpp/mxpp/main.py", line 381, in create_groupchat_room
     room = self.create_mapped_room(topic=self.groupchat_flag + room_jid)
   File "/opt/mxpp/mxpp/main.py", line 192, in create_mapped_room
     room = self.matrix.get_rooms()[room_id]
 KeyError: '!UXammuvubxymKebSvZ:XXXXXXXXXX.eu'

**Comment by anewusername** [comment]
Oops, I wasn't removing rooms from the jid -> room_id map when leaving them... should be fixed now.

**Comment by szimszon** [comment]
Confirmed. It works. Thank you. I also switched to Ubuntu 17.04 as docker base and python3.5.
