### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Madji** [anewusername/mxpp#7]
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/lib/python3.4/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/user-data/bridge/mxpp/mxpp/main.py", line 63
    self.xmpp = ClientXMPP(**self.xmpp_login, **self.xmpp_roster_options)
                                            ^
SyntaxError: invalid syntax

**Comment by anewusername** [comment]
This project requires python 3.5 or later.
